seed: 42

wandb:
  use: True
  entity: yixinzhou_ethz
  project: "Tree Species Identification"
  name: "FCOS_Res300_Run1"
  key: 78ca1f862ad9d2da640d58d1d18e1162a9358659

device: "auto"

paths:
  save_dir: "results/checkpoints"

data:
  dataset:
    folder: "data/TreeAI_Swiss_60/splits"
    target_size: [300, 300]
    s1_unit: "db"
    s2_fill: 0
    vhm_compute_method: "minus"
    sentinel_timestamp: "monthly"

train:
  validation: True
  batch_size: 16
  num_workers: 4
  epochs: 200
  lr: 1e-3

loss:
  sparse_ignore_threshold: 0.3

model:
  num_classes: 12
  fusion_channels: 256

checkpoint_path: "results/checkpoints/last_model.pth"
hydra:
  run:
    dir: logs/${now:%Y-%m-%d}/${now:%H-%M-%S}